Pose Estimation: PoseEstimation Class Reference
PoseEstimation Class Reference
Implements the procedure to achieve pose estimation of a given query object. The ideal procedure can be summarized as follows:
#include <PoseEstimation_interface.h>
Public Member Functions
PoseEstimation ()
Default Empty Constructor that sets default parameters (see them in config file "config/parameters.conf")
PoseEstimation (boost::shared_ptr< parameters > map)
Constructor with parameters to set.
PoseEstimation (boost::filesystem::path config_file)
Constructor with path to a configuration file containing parameters to set.
void estimate (string name, PC &cloud, boost::filesystem::path db_path)
Undergo the whole process of pose estimation.
void estimate (string name, PC::Ptr cloud_pointer, boost::filesystem::path db_path)
Undergo the whole process of pose estimation.
void estimate (string name, PC &cloud, PoseDB &database)
Undergo the whole process of pose estimation.
void estimate (string name, PC::Ptr cloud_pointer, PoseDB &database)
Undergo the whole process of pose estimation.
void generateLists (boost::filesystem::path dbPath)
Generates list(s) of candidates to the query using the database provided as argument.
void generateLists ()
Generates list(s) of candidates to the query using previously set database.
boost::shared_ptr< parameters > getParameters ()
Returns a shared pointer of a copy of parameters used by the pose estimation.
void initParams (boost::filesystem::path config_file)
Initialize the class with parameters found in config file.
void initParams (boost::shared_ptr< parameters > map)
Initialize parameters of PoseEstimation from the map provided.
void printCandidates ()
Print List of Candidates to the query on screen.
void printEstimation ()
Print final estimation informations (such as name, distance, rmse and transformation) on screen.
void printParams ()
Print current parameter values on screen.
void refineCandidates ()
Start the refinement procedure with ICP to obtain a final candidate from the composite list.
void resetViewpoint ()
Reset the viewpoint for current query, so that i can be computed again.
bool saveEstimation (boost::filesystem::path file, bool append=true)
Save final estimation informations (such as name, distance, rmse and transformation) on a file with path specified.
void setDatabase (boost::filesystem::path dbPath)
Set a database of known poses to be used for pose estimation procedure.
void setDatabase (PoseDB &database)
Set a database of known poses to be used for pose estimation procedure.
void setParam (string key, float value)
Set a parameter of the Class directly, knowing its name.
void setParam (string key, int value)
Set a parameter of the Class directly, knowing its name.
void setParam (string key, double value)
Set a parameter of the Class directly, knowing its name.
void setQuery (string str, PC &cl)
Set the Pose Estimation query (the object to be identified)
void setQuery (string str, PC::Ptr clp)
Set the Pose Estimation query (the object to be identified)
void setQueryViewpoint (float x, float y, float z)
Explicitly set the query viewpoint.
Private Member Functions
void computeCVFH_ ()
Internal method to compute CVFH feature of the query, internal use.
void computeESF_ ()
Internal method to compute ESF feature of the query, internal use.
bool computeNormals_ ()
Internal method to compute Surface Normals of the query, internal use, return true if success.
void computeOURCVFH_ ()
Internal method to compute OURCVFH feature of the query, internal use.
void computeVFH_ ()
Internal method to compute VFH feature of the query, internal use.
void downsampling_ ()
Internal method to downsample the query with VoxelGrid, internal use.
void filtering_ ()
Internal method to filter the query with Statistical Outlier Removal, internal use.
bool findCandidate_ (vector< Candidate > &list, string name, float &dist)
Searches a list for a candidate and eliminates it, saving its distance. internal use.
bool initQuery_ ()
Initialize the Query by computing preprocessing and features, returns true if success, internal use.
void setParam_ (string, string &)
Set a parameter of Pose Estimation from a string representing its value, used internally when reading parameters from a file.
void upsampling_ ()
Internal method to upsample the query with MLS Random Uniform Density, internal use.
Private Attributes
bool candidates_found_
vector< Candidate > composite_list_
PointCloud< VFHSignature308 > cvfh_
vector< Candidate > cvfh_list_
PoseDB database_
Database used for Pose Estimation.
bool db_set_
boost::filesystem::path dbPath_
Path to the directory containing the database of known poses, created previously.
PointCloud< ESFSignature640 > esf_
vector< Candidate > esf_list_
int feature_count_
Internal counter used to count how many feature the class uses.
PointCloud< Normal > normals_
PointCloud< VFHSignature308 > ourcvfh_
vector< Candidate > ourcvfh_list_
parameters params_
Map to store all parameters as key=value pairs.
boost::shared_ptr< Candidate > pose_estimation_
Pointer to the final Candidate that holds the pose estimation of the query.
PC::Ptr query_cloud_
The cloud pointer that represent the query to estimate as supplied before any computation.
PC::Ptr query_cloud_processed_
Cloud pointer to query pre-processed cloud (if preprocessing is made, otherwise it's the same as query_cloud.
string query_name_
The name of the query to estimate.
bool query_set_
bool refinement_done_
PointCloud< VFHSignature308 > vfh_
Containers that hold the query features.
vector< Candidate > vfh_list_
List of candidates to the query.
bool vp_supplied_
Internal parameters to check if various stages of pose estimation are completed correctly.
float vpx_
Viewpoint coordinates, used in computations like VFH and Normal estimation.
float vpy_
float vpz_
Detailed Description
Implements the procedure to achieve pose estimation of a given query object. The ideal procedure can be summarized as follows:
Initialize the class parameters either with the constructors or with initParams()
PoseEstimation pe; //empty constructor, default parameters are set
PoseEstimation pe2("config/params.config"); //constructor with path to a configuration file
pe.initParams("config/params.config"); //change all parameters specified in the configuration file
pe.setParam("verbosity", 2); //change parameter "verbosity" to 2
Set the query object to be identified with method setQuery() and the database to use with setDatabase()
PointCloud<PointXYZRGBA> cl;
loadPCDFile("cloud.pcd", cl);
pe.setQuery("funnel_20_30", cl); //set a new query to be a point cloud contained in "cl" and name it "funnel_20_30"
pe.setDatabase("../Database"); //load a database from disk contained in directory "../Database"
Generate the list(s) of candidates to the query with member generateLists()
pe.generateLists(); //list of candidates are computed, based on type of parameters set
Obtain the final candidate with member refineCandidates()
pe.refineCandidates(); //Select one final candidate from the lists, representing the pose estimation
Print, Get or Save the final pose estimation with the corresponding member functions
pe.saveEstimation("file.pose"); //Save the estimation to a file on disk
pe.printEstimation(); //print the estimation on screen
pe.viewEstimation(); //open a pcl visualizer to view the estimation
Alternatively the method estimate() can be called right after initialization with constructor
PoseEstimation pe;
PointCloud<PointXYZRGBA> cloud;
//...
//Put somethging in cloud
//...
pe.estimate("query object", cloud, "DB_PATH"); //calls setQuery(), setDatabase(), generateList(), refineCandidates()
Author
Federico Spinelli
Definition at line 271 of file PoseEstimation_interface.h.
Constructor & Destructor Documentation
PoseEstimation::PoseEstimation ()
Default Empty Constructor that sets default parameters (see them in config file "config/parameters.conf")
Definition at line 1162 of file PoseEstimation_interface.hpp.
PoseEstimation::PoseEstimation (boost::shared_ptr< parameters > map) inline
Constructor with parameters to set.
Parameters
[in] map Shared pointer to unordered_map containing parameters to use
NOTE: This constructor uses C++11 functionality and will probably not compile without -std=c++11 It delegates construction to empty contructor then calls initParams() It is the same way as calling empty constructor and then initParams() method
Definition at line 406 of file PoseEstimation_interface.h.
PoseEstimation::PoseEstimation (boost::filesystem::path config_file) inline
Constructor with path to a configuration file containing parameters to set.
Parameters
[in] config_file Path to a config file to use
Configuration file must have extension .conf and follow certain naming conventions, look at example .conf file provided for more details (i.e "config/parameters.conf") NOTE: This constructor uses C++11 functionality and will probably not compile without -std=c++11 It delegates construction to empty contructor then calls initParams() It is the same way as calling empty constructor and then initParams() method
Definition at line 417 of file PoseEstimation_interface.h.
Member Function Documentation
void PoseEstimation::computeCVFH_ () private
Internal method to compute CVFH feature of the query, internal use.
Definition at line 1562 of file PoseEstimation_interface.hpp.
References D2R.
void PoseEstimation::computeESF_ () private
Internal method to compute ESF feature of the query, internal use.
Definition at line 1541 of file PoseEstimation_interface.hpp.
bool PoseEstimation::computeNormals_ () private
Internal method to compute Surface Normals of the query, internal use, return true if success.
Definition at line 1417 of file PoseEstimation_interface.hpp.
References D2R.
void PoseEstimation::computeOURCVFH_ () private
Internal method to compute OURCVFH feature of the query, internal use.
Definition at line 1604 of file PoseEstimation_interface.hpp.
References D2R.
void PoseEstimation::computeVFH_ () private
Internal method to compute VFH feature of the query, internal use.
Definition at line 1509 of file PoseEstimation_interface.hpp.
void PoseEstimation::downsampling_ () private
Internal method to downsample the query with VoxelGrid, internal use.
Definition at line 1379 of file PoseEstimation_interface.hpp.
void PoseEstimation::estimate (string name, PC & cloud, boost::filesystem::path db_path)
Undergo the whole process of pose estimation.
Parameters
[in] name Name of the new query object to estimate
[in] cloud Point cloud containing the query object to estimate (segmented)
[in] db_path Path to a directory containing the database of poses to load
This method calls is sequence setQuery() setDatabase() generateLists() and refineCandidates(), using the already set parameters
Definition at line 2409 of file PoseEstimation_interface.hpp.
void PoseEstimation::estimate (string name, PC::Ptr cloud_pointer, boost::filesystem::path db_path)
Undergo the whole process of pose estimation.
Parameters
[in] name Name of the new query object to estimate
[in] cloud_pointer Pointer to a point cloud containing the query object to estimate (segmented)
[in] db_path Path to a directory containing the database of poses to load
This method calls is sequence setQuery() setDatabase() generateLists() and refineCandidates(), using the already set parameters
Definition at line 2417 of file PoseEstimation_interface.hpp.
void PoseEstimation::estimate (string name, PC & cloud, PoseDB & database)
Undergo the whole process of pose estimation.
Parameters
[in] name Name of the new query object to estimate
[in] cloud Point cloud containing the query object to estimate (segmented)
[in] database PoseDB object to use as database
This method calls is sequence setQuery() setDatabase() generateLists() and refineCandidates(), using the already set parameters
Definition at line 2425 of file PoseEstimation_interface.hpp.
void PoseEstimation::estimate (string name, PC::Ptr cloud_pointer, PoseDB & database)
Undergo the whole process of pose estimation.
Parameters
[in] name Name of the new query object to estimate
[in] cloud_pointer Pointer to a point cloud containing the query object to estimate (segmented)
[in] database PoseDB object to use as database
This method calls is sequence setQuery() setDatabase() generateLists() and refineCandidates(), using the already set parameters
Definition at line 2433 of file PoseEstimation_interface.hpp.
void PoseEstimation::filtering_ () private
Internal method to filter the query with Statistical Outlier Removal, internal use.
Definition at line 1311 of file PoseEstimation_interface.hpp.
bool PoseEstimation::findCandidate_ (vector< Candidate > & list, string name, float & dist) private
Searches a list for a candidate and eliminates it, saving its distance. internal use.
Parameters
[in] list The list to inspect and modifiy
[in] name The name to search in list
[out] dist The distace of Candidate found in list (normalized)
Return true if the candidate is found on the list, false otherwise
Definition at line 1786 of file PoseEstimation_interface.hpp.
void PoseEstimation::generateLists (boost::filesystem::path dbPath)
Generates list(s) of candidates to the query using the database provided as argument.
Parameters
[in] dbPath The path to the directory containing the database of poses, previously generated.
This member also sets the database to the one specified for future lists computations.
void PoseEstimation::generateLists ()
Generates list(s) of candidates to the query using previously set database.
Definition at line 1804 of file PoseEstimation_interface.hpp.
References Candidate::cloud_, Candidate::distance_, Candidate::getDistance(), Candidate::getNormalizedDistance(), Candidate::name_, Candidate::normalized_distance_, and Candidate::rank_.
boost::shared_ptr< parameters > PoseEstimation::getParameters ()
Returns a shared pointer of a copy of parameters used by the pose estimation.
Returned pointer can be modified but any changes are not reflected back to the class, use setParam() or initParams() to modify PoseEstimation parameters
Definition at line 2464 of file PoseEstimation_interface.hpp.
void PoseEstimation::initParams (boost::filesystem::path config_file)
Initialize the class with parameters found in config file.
Parameters
[in] config_file Path to a config file to use
Configuration file must have extension .conf and follow certain naming conventions, look at example .conf file provided for more details (i.e "config/parameters.conf")
void PoseEstimation::initParams (boost::shared_ptr< parameters > map)
Initialize parameters of PoseEstimation from the map provided.
Parameters
[in] map shared pointer to unordered_map containing parameters to use
unordered_map must contain valid keys and values, otherwise they will be ignored
Definition at line 1299 of file PoseEstimation_interface.hpp.
bool PoseEstimation::initQuery_ () private
Initialize the Query by computing preprocessing and features, returns true if success, internal use.
Definition at line 1654 of file PoseEstimation_interface.hpp.
void PoseEstimation::printCandidates ()
Print List of Candidates to the query on screen.
Definition at line 2200 of file PoseEstimation_interface.hpp.
void PoseEstimation::printEstimation ()
Print final estimation informations (such as name, distance, rmse and transformation) on screen.
Definition at line 2441 of file PoseEstimation_interface.hpp.
void PoseEstimation::printParams ()
Print current parameter values on screen.
Definition at line 1732 of file PoseEstimation_interface.hpp.
void PoseEstimation::refineCandidates ()
Start the refinement procedure with ICP to obtain a final candidate from the composite list.
Currently two methods for refinemente are implemented: Progressive Bisection (default) and Brute Force To chose Progressive Bisection set "progBisection" parameter to 1, to chose Brute Force set it to 0
Brute Force:
Start align rank 1 candidate on composite list with ICP, until "maxIterations" (default 200) are reached or candidate RMSE falls below "rmseThreshold" (default 0.003)
Align all the candidates until one converges, that one is the final pose estimation
If no one converges the Pose Estimation will produce no answer. Set an higher "rmseThreshold" parameter
Progressive Bisection:
Align all candidates on composite list with ICP, but performs at most "progItera" (default 5) iterations
Resort the list based on minimum RMSE of candidates
Discard a fraction of the list multiplying its size by "progFraction" (default 0.5), eliminating candidates with worst rmse
Repeat from step 1 until one candidates falls below the "rmseThreshold" (default 0.003) or only one candidate survives
Definition at line 2257 of file PoseEstimation_interface.hpp.
References Candidate::getRMSE().
void PoseEstimation::resetViewpoint () inline
Reset the viewpoint for current query, so that i can be computed again.
Definition at line 555 of file PoseEstimation_interface.h.
bool PoseEstimation::saveEstimation (boost::filesystem::path file, bool append = true)
Save final estimation informations (such as name, distance, rmse and transformation) on a file with path specified.
Parameters
[in] file Path to a location on disk, where the file will be created or renewed
[in] append Chose to append to the end of file (true)(default), or truncate its contents (false), if file does not exists this parameter has no effect
Returns
True if file is correctly written, False otherwise
The path can specify a directory or a file, if the former a new text file of name "query_name.estimation" will be created inside the specified directory. If the latter, the specified file will be written. Note on paths: if file path does not exists, a file must be specified with an extension, otherwise it will be treated as a directory. For example "/foo/bar" or "/foo/bar/" will be both treated as directories if they don't exists already. "foo/bar.f" will be treated as file "bar.f" inside relative directory "foo"
Definition at line 2472 of file PoseEstimation_interface.hpp.
void PoseEstimation::setDatabase (boost::filesystem::path dbPath)
Set a database of known poses to be used for pose estimation procedure.
Parameters
[in] dbPath The path to the directory containing the database
void PoseEstimation::setDatabase (PoseDB & database)
Set a database of known poses to be used for pose estimation procedure.
Parameters
[in] database PoseDB ojbect to use as database
Definition at line 1739 of file PoseEstimation_interface.hpp.
References PoseDB::isEmpty().
void PoseEstimation::setParam (string key, float value)
Set a parameter of the Class directly, knowing its name.
Parameters
[in] key the parameter name to change
[in] value the value that key should assume
Example Usage:
PoseEstimation pe; //construct and sets default parameters
pe.setParam("useVFH", 0); //pe now skips VFH computation for query
string str;
str = "verbosity";
pe.setParam(str, 2); //pe now has verbosity set to 2
Definition at line 1198 of file PoseEstimation_interface.hpp.
void PoseEstimation::setParam (string key, int value) inline
Set a parameter of the Class directly, knowing its name.
Parameters
[in] key the parameter name to change
[in] value the value that key should assume
Overloaded for ints
Definition at line 374 of file PoseEstimation_interface.h.
References setParam().
Referenced by setParam().
void PoseEstimation::setParam (string key, double value) inline
Set a parameter of the Class directly, knowing its name.
Parameters
[in] key the parameter name to change
[in] value the value that key should assume
Overloaded for double
Definition at line 382 of file PoseEstimation_interface.h.
References setParam().
Referenced by setParam().
void PoseEstimation::setParam_ (string key, string & value) private
Set a parameter of Pose Estimation from a string representing its value, used internally when reading parameters from a file.
Definition at line 1233 of file PoseEstimation_interface.hpp.
void PoseEstimation::setQuery (string str, PC & cl)
Set the Pose Estimation query (the object to be identified)
Parameters
[in] str The name the query should assume
[in] cl Point cloud containing only the object to be estimated (i.e. already segmented)
Definition at line 1710 of file PoseEstimation_interface.hpp.
void PoseEstimation::setQuery (string str, PC::Ptr clp)
Set the Pose Estimation query (the object to be identified)
Parameters
[in] str the name the query should assume
[in] clp Shared pointer containing only the pointcloud of the object to be estimated (i.e. already segmented)
Definition at line 1721 of file PoseEstimation_interface.hpp.
void PoseEstimation::setQueryViewpoint (float x, float y, float z)
Explicitly set the query viewpoint.
Parameters
[in] x Coordinate x of the viewpoint
[in] y Coordinate y of the viewpoint
[in] z Coordinate z ot the viewpoint
THIS METHOD OVERRIDES ANY VIEWPOINT PARAMETERS SET, thus Pose Estimation will ignore "useSOasViewpoint" and "computeViewpointFromName" parameters regardless of their value, and will use the viewpoint set this way for the computations where a viewpoint is needed (normals, VFH, CVFH ...) This method should be used only if the the viewpoint cannot be obtained from sensor_origin of query cloud or if it cannot be computed from query name (i.e. the above cited parameters failed to set it correctly) The recommended and preferred way is to use the sensor_origin field, so prepare your query cloud accordingly and use the "useSOasViewpoint" parameter instead of this method
Definition at line 1409 of file PoseEstimation_interface.hpp.
void PoseEstimation::upsampling_ () private
Internal method to upsample the query with MLS Random Uniform Density, internal use.
Definition at line 1339 of file PoseEstimation_interface.hpp.
Member Data Documentation
bool PoseEstimation::candidates_found_ private
Definition at line 303 of file PoseEstimation_interface.h.
vector<Candidate> PoseEstimation::composite_list_ private
Definition at line 294 of file PoseEstimation_interface.h.
PointCloud<VFHSignature308> PoseEstimation::cvfh_ private
Definition at line 306 of file PoseEstimation_interface.h.
vector<Candidate> PoseEstimation::cvfh_list_ private
Definition at line 294 of file PoseEstimation_interface.h.
PoseDB PoseEstimation::database_ private
Database used for Pose Estimation.
Definition at line 276 of file PoseEstimation_interface.h.
bool PoseEstimation::db_set_ private
Definition at line 303 of file PoseEstimation_interface.h.
boost::filesystem::path PoseEstimation::dbPath_ private
Path to the directory containing the database of known poses, created previously.
Definition at line 297 of file PoseEstimation_interface.h.
PointCloud<ESFSignature640> PoseEstimation::esf_ private
Definition at line 307 of file PoseEstimation_interface.h.
vector<Candidate> PoseEstimation::esf_list_ private
Definition at line 294 of file PoseEstimation_interface.h.
int PoseEstimation::feature_count_ private
Internal counter used to count how many feature the class uses.
Definition at line 282 of file PoseEstimation_interface.h.
PointCloud<Normal> PoseEstimation::normals_ private
Definition at line 308 of file PoseEstimation_interface.h.
PointCloud<VFHSignature308> PoseEstimation::ourcvfh_ private
Definition at line 306 of file PoseEstimation_interface.h.
vector<Candidate> PoseEstimation::ourcvfh_list_ private
Definition at line 294 of file PoseEstimation_interface.h.
parameters PoseEstimation::params_ private
Map to store all parameters as key=value pairs.
Definition at line 273 of file PoseEstimation_interface.h.
boost::shared_ptr<Candidate> PoseEstimation::pose_estimation_ private
Pointer to the final Candidate that holds the pose estimation of the query.
Definition at line 279 of file PoseEstimation_interface.h.
PC::Ptr PoseEstimation::query_cloud_ private
The cloud pointer that represent the query to estimate as supplied before any computation.
Definition at line 288 of file PoseEstimation_interface.h.
PC::Ptr PoseEstimation::query_cloud_processed_ private
Cloud pointer to query pre-processed cloud (if preprocessing is made, otherwise it's the same as query_cloud.
Definition at line 291 of file PoseEstimation_interface.h.
string PoseEstimation::query_name_ private
The name of the query to estimate.
Definition at line 285 of file PoseEstimation_interface.h.
bool PoseEstimation::query_set_ private
Definition at line 303 of file PoseEstimation_interface.h.
bool PoseEstimation::refinement_done_ private
Definition at line 303 of file PoseEstimation_interface.h.
PointCloud<VFHSignature308> PoseEstimation::vfh_ private
Containers that hold the query features.
Definition at line 306 of file PoseEstimation_interface.h.
vector<Candidate> PoseEstimation::vfh_list_ private
List of candidates to the query.
Definition at line 294 of file PoseEstimation_interface.h.
bool PoseEstimation::vp_supplied_ private
Internal parameters to check if various stages of pose estimation are completed correctly.
Definition at line 303 of file PoseEstimation_interface.h.
float PoseEstimation::vpx_ private
Viewpoint coordinates, used in computations like VFH and Normal estimation.
Definition at line 300 of file PoseEstimation_interface.h.
float PoseEstimation::vpy_ private
Definition at line 300 of file PoseEstimation_interface.h.
float PoseEstimation::vpz_ private
Definition at line 300 of file PoseEstimation_interface.h.
The documentation for this class was generated from the following files:
include/PoseEstimation_interface.h
include/PoseEstimation_interface.hpp