Pose Estimation: Candidate Class Reference
Candidate Class Reference
Describes a single candidate object to the query.
#include <PoseEstimation_interface.h>
Public Member Functions
Candidate ()
Default empty Constructor.
Candidate (string str, PC &cl)
Constructor with name and cloud.
Candidate (string str, PC::Ptr clp)
Constructor with name and cloud pointer.
void getDistance (float &d) const
Get the distance of Candidate from Query in the metric chosen by the feature.
void getNormalizedDistance (float &d) const
Get the Normalize distance of Candidate from Query.
void getRank (int &r) const
Get Candidate Rank in the list of candidates.
void getRMSE (float &e) const
Get Root Mean Square Error of Candidate as it was after the refinement.
void getTransformation (Eigen::Matrix4f &t) const
Get Homogeneous Transformation that brings the Candidate over the Query.
Private Attributes
PC::Ptr cloud_
float distance_
string name_
float normalized_distance_
int rank_
float rmse_
Eigen::Matrix4f transformation_
Friends
class PoseEstimation
Detailed Description
Describes a single candidate object to the query.
This class is used internally by PoseEstimation, a few methods are present to look at rank, distance, RMSE and transformation, if needed. However it is not meant to be used directly
Author
Federico Spinelli
Definition at line 171 of file PoseEstimation_interface.h.
Constructor & Destructor Documentation
Candidate::Candidate ()
Default empty Constructor.
Definition at line 1092 of file PoseEstimation_interface.hpp.
Candidate::Candidate (string str, PC & cl)
Constructor with name and cloud.
Parameters
[in] str The object name the candidate will have
[in] cl Point cloud which holds the object
Definition at line 1102 of file PoseEstimation_interface.hpp.
Candidate::Candidate (string str, PC::Ptr clp)
Constructor with name and cloud pointer.
Parameters
[in] str The object name the candidate will have
[in] clp Shared pointer to the point cloud that contains the object Note that clp parameter should not be empty pointer, or the contructor will throw an error
Definition at line 1113 of file PoseEstimation_interface.hpp.
Member Function Documentation
void Candidate::getDistance (float & d) const
Get the distance of Candidate from Query in the metric chosen by the feature.
Parameters
[out] d The distance the candidate has from the query
Definition at line 1136 of file PoseEstimation_interface.hpp.
Referenced by PoseEstimation::generateLists().
void Candidate::getNormalizedDistance (float & d) const
Get the Normalize distance of Candidate from Query.
Parameters
[out] d The distance the candidate has from the query Normalized distances range from 0 to 1, zero at "rank 1" and one at "rank k"
Definition at line 1142 of file PoseEstimation_interface.hpp.
Referenced by PoseEstimation::generateLists().
void Candidate::getRank (int & r) const
Get Candidate Rank in the list of candidates.
Parameters
[out] r The rank the candidate has in the list
Definition at line 1130 of file PoseEstimation_interface.hpp.
void Candidate::getRMSE (float & e) const
Get Root Mean Square Error of Candidate as it was after the refinement.
Parameters
[out] e The Root Mean Square Error of the Candidate
Definition at line 1148 of file PoseEstimation_interface.hpp.
Referenced by PoseEstimation::refineCandidates().
void Candidate::getTransformation (Eigen::Matrix4f & t) const
Get Homogeneous Transformation that brings the Candidate over the Query.
Parameters
[out] t Transformation that brings the Candidate over the Query The transformation is expressed in the Candidate Reference System
Definition at line 1154 of file PoseEstimation_interface.hpp.
Friends And Related Function Documentation
friend class PoseEstimation friend
Definition at line 173 of file PoseEstimation_interface.h.
Member Data Documentation
PC::Ptr Candidate::cloud_ private
Definition at line 175 of file PoseEstimation_interface.h.
Referenced by PoseEstimation::generateLists().
float Candidate::distance_ private
Definition at line 177 of file PoseEstimation_interface.h.
Referenced by PoseEstimation::generateLists().
string Candidate::name_ private
Definition at line 174 of file PoseEstimation_interface.h.
Referenced by PoseEstimation::generateLists().
float Candidate::normalized_distance_ private
Definition at line 178 of file PoseEstimation_interface.h.
Referenced by PoseEstimation::generateLists().
int Candidate::rank_ private
Definition at line 176 of file PoseEstimation_interface.h.
Referenced by PoseEstimation::generateLists().
float Candidate::rmse_ private
Definition at line 179 of file PoseEstimation_interface.h.
Eigen::Matrix4f Candidate::transformation_ private
Definition at line 180 of file PoseEstimation_interface.h.
The documentation for this class was generated from the following files:
include/PoseEstimation_interface.h
include/PoseEstimation_interface.hpp